export const GET_CAN_REQ_DATA = 'GET_CAN_REQ_DATA';
export const GET_REG_VOTER_DATA = 'GET_REG_VOTER_DATA'; 
export const APPROVE_CAN_DATA = 'APPROVE_CAN_DATA'; 
export const GET_ALL_VOTE_COUNT_DATA = 'GET_ALL_VOTE_COUNT_DATA';
export const DELETE_PARTICULAR_REQ_DATA = 'DELETE_PARTICULAR_REQ_DATA';
///****ADMIN_TYPES */
export const SET_ADMIN_DETAILS = 'SET_ADMIN_DETAILS';
export const SET_ADMIN_VOTING_TIME='SET_ADMIN_VOTING_TIME';
export const IS_LOADIND_LAODER = 'IS_LOADIND_LAODER'; 
////** END OF ADMIN */

export const CHECK_NOW ='CHECK_NOW';
export const IS_LOGIN_PAGE = 'IS_LOGIN_PAGE'; 
export const CHECK_PAGE_STATE = 'CHECK_PAGE_STATE';
export const TOGGLE_OPEN_AND_CLOSE = 'TOGGLE_OPEN_AND_CLOSE'; 
export const RETAIN_PAGE_ACTIVE_LINK = 'RETAIN_PAGE_ACTIVE_LINK';
export const GET_CANDIDATE_REQUEST_DATA = 'GET_CANDIDATE_REQUEST_DATA';
export const DELETE_CANDIDATE_REQUEST = 'DELETE_CANDIDATE_REQUEST'; 
export const GET_CAN_DATA = 'GET_CAN_DATA'; 
export const GET_APPROVED_DATA = 'GET_APPROVED_DATA';
export const GET_VOTE_COUNT_DATA = 'GET_VOTE_COUNT_DATA'; 
export const GET_COUNT_DATA = 'GET_COUNT_DATA'; 
export const GET_REGISTERED_VOTERS = 'GET_REGISTERED_VOTERS';
 

/****************END shared action types */

export const CHECK_VOTER_ELIGIBILITY = 'CHECK_VOTER_ELIGIBILITY'; 
export const VALID_EMAIL_SEND_MESSAGE = 'VALID_EMAIL_SEND_MESSAGE';
export const INVALID_EMAIL_ERROR_APPEAR = 'INVALID_EMAIL_ERROR_APPEAR';
export const EXISTING_EMAIL_ERROR_APPEAR = 'EXISTING_EMAIL_ERROR_APPEAR';

/**********END VOTING ELIGIBILTY MODULE ACTION TYPES */

/********** USER_DETAILS FOR REDUX*/
export const CHANGE_USER_IMAGE ='CHANGE_USER_IMAGE'; 
export const GET_USER_FORM_DATA = 'GET_USER_FORM_DATA';
export const CHECK_WHEN_DATA_HAS_COLLECT = 'CHECK_WHEN_DATA_HAS_COLLECT';
///******end */

/////*********** ADMIN ACTIONS  */
export const SET_ADMIN_USER = 'SET_ADMIN_USER';
/////**** */

export const FLASH_MASSAGE = 'FLASH_MESSAGE';
export const UPDATE_CURRENT_USER= 'UPDATE_CURRENT_USER';
export const SET_CURRENT_USER ='SET_CURRENT_USER';
export const SET_USER_DETAILS = 'SET_USER_DETAILS';
export const SET_CRIME_REPORTS = 'SET_CRIME_REPORTS';
export const SET_MISSING_REPORTS = 'SET_MISSING_REPORTS';
export const SET_COMPLAINT_REPORTS = 'SET_COMPLAINT_REPORTS';
export const SET_ALL_USER_CRIME_REPORTS ='SET_ALL_USER_CRIME_REPORTS';
export const SET_ALL_USER_MISS_REPORTS= 'SET_ALL_USER_MISS_REPORTS' ;
export const SET_ALL_USER_COMPLAINT_REPORTS ='SET_ALL_USER_COMPLAINT_REPORTS';